### ISSUE TITLE
Plots.jl dependency

### ISSUE THREAD

**Issue by simsurace** [ManuelStapper/CountTimeSeries.jl#6]
This is a very nice package! However, the Plots.jl dependency is quite heavy. Would it be possible to put the plotting functions in a separate package in order to reduce the weight of this one?

**Comment by ManuelStapper** [comment]
Hi, thanks for the feedback! I guess it's a good idea, since Plots is only used for the output of pit() and nowhere else.
I'll double check and remove Plots from dependencies.

**Comment by simsurace** [comment]
Thanks for the very prompt reply! That would be awesome!

**Comment by simsurace** [comment]
Fixed on master.
